---
apiVersion: v1
kind: Namespace
metadata:
  name: mlm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlm
  namespace: mlm
  labels:
    tags.datadoghq.com/env: "prod" # Unified service tag - Pod Env tag
    tags.datadoghq.com/service: "mlm" # Unified service tag - Pod Service tag
    tags.datadoghq.com/version: "1.0" # Unified service tag - Pod Version tag
spec:
  selector:
    matchLabels:
      app: mlm
  replicas: 1
  template:
    metadata:
      labels:
        app: mlm
        tags.datadoghq.com/env: "prod" # Unified service tag - Pod Env tag
        tags.datadoghq.com/service: "mlm" # Unified service tag - Pod Service tag
        tags.datadoghq.com/version: "1.0" # Unified service tag - Pod Version tag
        admission.datadoghq.com/enabled: "true" # Enable Admission Controller to mutate new pods in this deployment
      annotations:
        admission.datadoghq.com/js-lib.version: "latest"
    spec:
      containers:
      - image: mmoraesc/desafio-ml-mlm:latest
        imagePullPolicy: Always
        name: mlm
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
          - name: APP_NAME
            valueFrom:
              configMapKeyRef:
                name: configmap-api
                key: APP_NAME
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: configmap-api
                key: DB_PORT
          - name: DB_NOME
            valueFrom:
              configMapKeyRef:
                name: configmap-api
                key: DB_NOME
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: configmap-api
                key: DB_URL
          - name: DB_USUARIO
            valueFrom:
              configMapKeyRef:
                name: configmap-api
                key: DB_USUARIO      
          - name: API_PORT
            valueFrom:
              configMapKeyRef:
                name: configmap-api
                key: API_PORT
          - name: DB_SENHA
            valueFrom:
              secretKeyRef:
                name: secret-db-api
                key: DB_SENHA
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_LOGS_INJECTION
            value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: mlm
  namespace: mlm
spec:
  ports:
  - targetPort: 8080 
    port: 7000
    nodePort: 30004
    protocol: TCP
  type: NodePort
  selector:
    app: mlm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-api
  namespace: mlm
data:
  APP_NAME: "mlm"
  DB_PORT: "3306"
  DB_USUARIO: "defiml"
  DB_URL: "defiml.ccun5hhq8u6l.us-east-1.rds.amazonaws.com"
  DB_NOME: "mlm"
  API_PORT: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-db-api
  namespace: mlm
type: Opaque
data:
  DB_SENHA: Hagnar469425 